call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

set nocompatible
set enc=utf-8

""""""""""""""""""""""""""""""""""""""
"            Appearance              "
""""""""""""""""""""""""""""""""""""""
set ruler                   " line numbers, rulers, and everything else
set vb                      " Visual bell
set lazyredraw              " Don't update while in macro
set ttyfast                 " Improves redrawing
set titlestring=%f title    " Display filename in terminal window
set rulerformat=%l:%c ruler " Display current column/line
set showcmd                 " Show commands at bottom right
set splitbelow              " Split windows BELOW current window!
set winminheight=0          " Window minimum height
set scrolloff=8             " always have at least 8 lines before the window's bottom
"set foldcolumn=3            " 2 lines of column for fold showing, always
"set foldmethod=syntax
"set foldlevelstart=99
set statusline=[%02n]\ %f\ %(\[%M%R%H]%)%=\ %4l,%02c%2V\ %P%* " Set status line"
set laststatus=2            " Always display a status line at the bottom of the window"

""""""""""""""""""""""""""""""""""""""
"  Search & Replace
""""""""""""""""""""""""""""""""""""""
set hlsearch   " highlight searches
set ignorecase " make searches case-insensitive, unless they contain upper-case letters:
set smartcase
set incsearch  " show the `best match so far' as search strings are typed:
set gdefault   " assume the /g flag on :s substitutions to replace all matches in a line:
set showmatch  " Show the matching bracket for the last ')'"


""""""""""""""""""""""""""""""""""""""
" Whitespace, indention 
""""""""""""""""""""""""""""""""""""""
set list
set listchars=tab:>.
set autoindent smartindent
set shiftwidth=4
set tabstop=4
set expandtab
set smarttab

syntax on
filetype plugin indent on

set pastetoggle=<F12>

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

" Move Backup Files to ~/.vim/sessions
set backupdir=~/.vim/sessions
set dir=~/.vim/sessions

" Turn off annoying swapfiles
set noswapfile

" Set persistent undo (v7.3 only)
"set undodir=~/.vim/undodir
"set undofile
" keep 50 lines of command line history
set history=50

" Java specific stuff
let java_highlight_all=1
let java_highlight_debug=1
let java_ignore_javadoc=1
let java_highlight_functions=1
let java_mark_braces_in_parens_as_errors=1

" highlight strings inside C comments
let c_comment_strings=1

" ************************************************************************
" C O M M A N D S
"

"switch to directory of current file
command! CD cd %:p:h

" ************************************************************************
" K E Y   M A P P I N G S
"
map <Leader>e :Explore<cr>
map <Leader>s :Sexplore<cr> 

" pressing < or > will let you indent/unident selected lines
vnoremap < <gv
vnoremap > >gv

" Don't use Ex mode, use Q for formatting
map Q gq

" Make tab in v mode work like I think it should (keep highlighting):
vmap <tab> >gv
vmap <s-tab> <gv

" Map <c-s> to write current buffer.
map <c-s> :w<cr>
imap <c-s> <c-o><c-s>
imap <c-s> <esc><c-s>

" Buffer naviation
map <M-Left> :bprevious<CR>
map <M-Right> :bnext<CR>

" Select all.
map <c-a> ggVG

" Undo in insert mode.
imap <c-z> <c-o>u

" ************************************************************************
" B E G I N  A U T O C O M M A N D S
"
if has("autocmd")

  " When editing a file, always jump to the last known cursor position.
  " Don't do it when the position is invalid or when inside an event handler
  " (happens when dropping a file on gvim).
  autocmd BufReadPost *
    \ if line("'\"") > 0 && line("'\"") <= line("$") |
    \   exe "normal g`\"" |
    \ endif

  " Normally don't automatically format 'text' as it is typed, only do this
  " with comments, at 79 characters.
  au BufNewFile,BufEnter *.c,*.h,*.java,*.jsp set formatoptions-=t tw=79

endif " has("autocmd")
